otro fix

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -48,36 +48,42 @@ jobs:
       # 5. Despliegue en el servidor AWS
       - name: Deploy to AWS Server
         uses: appleboy/ssh-action@v1.2.0
+        run: echo "TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV
         with:
           host: ${{ secrets.AWS_SERVER_IP }}
           username: ${{ secrets.AWS_SERVER_USER }}
           key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
           port: 22
-          script: |
-            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
-            
-            echo "DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME"
-            echo "TAG: $TAG"
+        script: |
+          echo "DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME"
+          echo "TAG: $TAG"
 
-            sudo docker pull $DOCKER_IMAGE_NAME:$TAG
+          # Validar que las variables no estén vacías
+          if [[ -z "$DOCKER_IMAGE_NAME" || -z "$TAG" ]]; then
+            echo "ERROR: DOCKER_IMAGE_NAME o TAG están vacíos."
+            exit 1
+          fi
 
-            # Detener y eliminar el contenedor actual (si existe)
-            if [ $(sudo docker ps -a -q -f name=bff) ]; then
-              echo "Deteniendo y eliminando el contenedor existente 'bff'..."
-              sudo docker stop bff
-              sudo docker rm bff
-            else
-              echo "El contenedor 'bff' no existe, continuando..."
-            fi
+          # Descargar la imagen desde Docker Hub
+          sudo docker pull $DOCKER_IMAGE_NAME:$TAG
 
-            # Correr el contenedor con las variables de entorno
-            sudo docker run -d --name bff \
-              -p 8084:8084 \
-              --env cors.allowed-origins=${{ secrets.CORS_ALLOWED_ORIGINS }} \
-              --env server.port=8084 \
-              --env spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${{ secrets.JWK_SET_URI }} \
-              --env spring.application.name=bff \
-              --env api.doctors=http://doctor-service:8081 \
-              --env api.patient=http://paciente-service:8082 \
-              --env api.measurement=http://signos-service:8083 \
-              $DOCKER_IMAGE_NAME:$TAG
+          # Detener y eliminar el contenedor actual (si existe)
+          if [ $(sudo docker ps -a -q -f name=bff) ]; then
+            echo "Deteniendo y eliminando el contenedor existente 'bff'..."
+            sudo docker stop bff
+            sudo docker rm bff
+          else
+            echo "El contenedor 'bff' no existe, continuando..."
+          fi
+
+          # Correr el contenedor con las variables de entorno
+          sudo docker run -d --name bff \
+            -p 8084:8084 \
+            --env cors.allowed-origins=${{ secrets.CORS_ALLOWED_ORIGINS }} \
+            --env server.port=8084 \
+            --env spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${{ secrets.JWK_SET_URI }} \
+            --env spring.application.name=bff \
+            --env api.doctors=http://doctor-service:8081 \
+            --env api.patient=http://paciente-service:8082 \
+            --env api.measurement=http://signos-service:8083 \
+            $DOCKER_IMAGE_NAME:$TAG
